Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -39,7 +39,12 @@ jobs:
         with:
           python-version: '3.8.x'
           architecture: 'x64'
-
+          
+      - name: Check python style
+        run: |
+          python3 -m pip install autopep8
+          autopep8 -a -r -d --exit-code ./ort_aot || ( echo '::error title=Style issues::Please run \"autopep8 -a -r -i ./python\"' ; exit 1 )
+          
       # Runs a single command using the runners shell
       - name: install python package
         run: |
